### PR TITLE
HARP-9413 Fixes #1384 far plane too close in globe

### LINKED ISSUE #1384: [bug] Surfaces culled although they should be in view
**Describe the bug**

Looks like after certain interactions with the globe, the surfaces get erroneously culled at the edges of the screen.

**To Reproduce**

1. Zoom all the way in, out, in
2. Eventually it happens.

**Expected behavior**

There should be no culling at the edge of the viewport.

**Screenshots**

Here's a screen recording: https://youtu.be/Bv1pBGnFvuU

In the video, as I zoom in, you can see the black space come in from the edge of viewport.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Linux
 - Browser [e.g. chrome, safari] - Firefox
 - Version [e.g. 22] -

### PR DESCRIPTION
**Pull request by nzjony**
The far plane was being computed too close when the aspect ratio was close to one

The fix is to shoot a ray from the camera along the frustums upper right edge and see if it
intersects the earths sphere. Whether there is an intersection determines how restrictive the far
plane is.

### CODE REVIEW

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 1]
```diff
@@ -424,8 +435,14 @@ export class TopViewClipPlanesEvaluator extends ElevationBasedClipPlanesEvaluato
             // which is definitely closer than the tangent point mentioned above.
             const cam = camera as THREE.PerspectiveCamera;
             // Take fov directly if it is vertical, otherwise we translate it using aspect ratio:
-            const aspect = cam.aspect > 1 ? cam.aspect : 1 / cam.aspect;
-            const halfFovAngle = THREE.MathUtils.degToRad((cam.fov * aspect) / 2);
```
Comment (nzjony) [inline @here/harp-mapview/lib/ClipPlanesEvaluator.ts:428]: `cam.fov * aspect` is completely false, hence needing the focal length

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 2]
```diff
@@ -877,7 +897,7 @@ export class TiltViewClipPlanesEvaluator extends TopViewClipPlanesEvaluator {
             // Step-wise calculate angle between camera eye vector and tangent
 
             // Calculate angle between surface normal(below camera position) and tangent.
-            const alpha = Math.asin(r / d);
```
Comment (nzjony) [inline @here/harp-mapview/lib/ClipPlanesEvaluator.ts:880]: This is also completely wrong, the r & d values are othogonal to each other, neither is the hypotenuse, hence `atan` is the only valid way to calculate the angle.

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 3]
```diff
@@ -113,7 +116,7 @@ export class InterpolatedClipPlanesEvaluator implements ClipPlanesEvaluator {
             // the camera is looking at the center of the scene.
             const r = EarthConstants.EQUATORIAL_RADIUS;
             const d = camera.position.length();
-            const alpha = Math.asin(r / d);
+            const alpha = Math.atan(r / d);
```
Comment (atomicsulfate) [inline @here/harp-mapview/lib/ClipPlanesEvaluator.ts:119]: This alpha is the angle from the camera position to the tangent point on the sphere right?

   `          
   
                    , - ~ ~ ~ - ,
              , '                     '   ,        
            ,           .                  ,      
           ,            .                    ,   
          ,             .                     ,  
          ,             . O '                , 
          ,               | .                 ,  
           ,              |   .  r            ,
            ,             |      .           ,
              ,           |        ,       '_____ far
          /       ' -_, _ | _ ,  ' @ / T
              near        |        /
                          |       / t
                      d   |     /
                          |   /
                          |  / <--- alpha
                           E
`
The angle between the earth radius (r) and the tangent ray (t) is a right angle (@), therefore they are the legs of a right triangle. Alpha is the angle between the hypothenuse (d) and the tangent ray , so it's sinus is the opposite leg divided by the hypothenuse:  alpha = asin(r/d)

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 4]
```diff
@@ -416,16 +427,22 @@ export class TopViewClipPlanesEvaluator extends ElevationBasedClipPlanesEvaluato
             // always at world origin and camera orbits around it we have (see
             // #getTangentBasedFarPlane):
             // angle(OTC) = 90
-            // sin(OCT) = sin(alpha) = r / d
-            // alpha = asin(r / d)
-            const alpha = Math.asin(r / d);
+            // tan(OCT) = tan(alpha) = r / d
+            // alpha = atan(r / d)
+            const alpha = Math.atan(r / d);
```
Comment (atomicsulfate) [inline @here/harp-mapview/lib/ClipPlanesEvaluator.ts:432]: ditto

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 5]
```diff
@@ -877,7 +897,7 @@ export class TiltViewClipPlanesEvaluator extends TopViewClipPlanesEvaluator {
             // Step-wise calculate angle between camera eye vector and tangent
 
             // Calculate angle between surface normal(below camera position) and tangent.
-            const alpha = Math.asin(r / d);
+            const alpha = Math.atan(r / d);
```
Comment (atomicsulfate) [inline @here/harp-mapview/lib/ClipPlanesEvaluator.ts:900]: ditto

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts (hunk 2 above)
Comment (atomicsulfate) [reply @here/harp-mapview/lib/ClipPlanesEvaluator.ts:880]: that's not right, see my comment above.

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 6]
```diff
@@ -886,11 +906,10 @@ export class TiltViewClipPlanesEvaluator extends TopViewClipPlanesEvaluator {
             const modifiedAlpha = Math.abs(alpha - cameraPitch);
 
             // Use tangent based far plane if horizon is within field of view
-            const farTangent = this.getTangentBasedFarPlane(camera, d, r, modifiedAlpha);
-            farPlane =
-                halfFovAngle >= modifiedAlpha
-                    ? farTangent
-                    : this.getTiltedFovBasedFarPlane(d, r, halfFovAngle, cameraPitch);
+            const horizonWithinView = halfDiagonalFovAngle >= modifiedAlpha;
```
Comment (atomicsulfate) [inline @here/harp-mapview/lib/ClipPlanesEvaluator.ts:909]: This is not right anymore. Before, since we were testing the visibility of the tangent point at the top of the view, alpha (the angle from normal to tangent) was reduced by the camera pitch, which is a vertical angle. Now that we test the visibility of a tangent point in the top right view corner, we can't substract the camera pitch angle just like that, since it's not in the same direction as the angle to the new tangent point.

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts (hunk 3 above)
Comment (nzjony) [reply @here/harp-mapview/lib/ClipPlanesEvaluator.ts:119]: Thank you, yes I interpreted the ascii diagram wrong and came to the wrong conclusion, I will revert.

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 7]
```diff
@@ -416,16 +427,22 @@ export class TopViewClipPlanesEvaluator extends ElevationBasedClipPlanesEvaluato
...
             // Take fov directly if it is vertical, otherwise we translate it using aspect ratio:
-            const aspect = cam.aspect > 1 ? cam.aspect : 1 / cam.aspect;
-            const halfFovAngle = THREE.MathUtils.degToRad((cam.fov * aspect) / 2);
+
+            let halfFovAngle = THREE.MathUtils.degToRad(cam.fov / 2);
+            // If width > height, then we have to compute the horizontal FOV.
+            if (cam.aspect > 1) {
+                const halfPixelHeight = Math.tan(halfFovAngle) * focalLength;
+                const halfPixelWidth = halfPixelHeight * cam.aspect;
+                halfFovAngle = Math.atan(halfPixelWidth / focalLength);
```
[the remark this answers is not in the document]
Comment (nzjony) [reply @here/harp-mapview/lib/ClipPlanesEvaluator.ts:444]: Thank you

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts (hunk 6 above)
Comment (nzjony) [reply @here/harp-mapview/lib/ClipPlanesEvaluator.ts:909]: Thanks, I will fix.

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 8]
```diff
@@ -853,19 +861,6 @@ export class TiltViewClipPlanesEvaluator extends TopViewClipPlanesEvaluator {
...
-        if (camera instanceof THREE.PerspectiveCamera) {
-            // Take fov directly if it is vertical, otherwise we translate it using aspect ratio:
-            const aspect = camera.aspect > 1 ? camera.aspect : 1 / camera.aspect;
-            halfFovAngle = THREE.MathUtils.degToRad((camera.fov * aspect) / 2);
-
-            // Now we need to account for camera tilt and frustum volume, so the longest
-            // frustum edge does not intersects with sphere, it takes the worst case
-            // scenario regardless of camera tilt, so may be improved little bit with more
-            // sophisticated algorithm.
-            viewRanges.near *= Math.cos(halfFovAngle);
```
Comment (nzjony) [inline @here/harp-mapview/lib/ClipPlanesEvaluator.ts:866]: This is moved down into the next if statement

**Comment by nzjony** [comment]
@harpgl-bot retest this please

**Comment by nzjony** [comment]
@harpgl-bot retest this please

**Comment by nzjony** [comment]
@harpgl-bot retest this please

**Comment by nzjony** [comment]
@harpgl-bot retest this please

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 9]
```diff
@@ -874,6 +869,24 @@ export class TiltViewClipPlanesEvaluator extends TopViewClipPlanesEvaluator {
         const d = cameraToOrigin.length();
         let farPlane: number;
         if (camera instanceof THREE.PerspectiveCamera) {
+            const halfVerticalFovAngle = THREE.MathUtils.degToRad(camera.fov / 2);
+
+            // Ratio of the height of the camera compared to the distance between the center of the
+            // screen and the middle of the top of the screen (here set to be value 1). We just need
+            // this to be a ratio because we are interested in just computing the direction of the
+            // upper right corner and not any specific length.
+            const height = 1 / Math.tan(halfVerticalFovAngle);
```
Comment (atomicsulfate) [inline @here/harp-mapview/lib/ClipPlanesEvaluator.ts:878]: It took me a while to understand what you meant by height here. Since you are making a vector in camera space, height sounds related to camera y axis, not z axis like here.
I'd call it 'distance' or 'z'. The height here would be 1.

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts [hunk 10]
```diff
@@ -874,6 +869,24 @@ export class TiltViewClipPlanesEvaluator extends TopViewClipPlanesEvaluator {
...
+
+            // Screen space direction vector pointing to the top right frustum point from the camera
```
Comment (atomicsulfate) [inline @here/harp-mapview/lib/ClipPlanesEvaluator.ts:880]: Rather camera space.

**Review by atomicsulfate — APPROVED** [review]

File: @here/harp-mapview/lib/ClipPlanesEvaluator.ts (hunk 9 above)
Comment (nzjony) [reply @here/harp-mapview/lib/ClipPlanesEvaluator.ts:878]: Good point, I will rename.

**Review by atomicsulfate — APPROVED** [review]
